### PR TITLE
Issue #26 Fix for FilthMergeError

### PR DESCRIPTION
**Pull request by hugofvs**
MergeFilth was not having in count filths that are substrings of others.
This can be fixed by sorting the filths not only per starting position but also having the inclusive filths first.

### CODE REVIEW

**Comment by deanmalmgren** [comment]
This is fantastic! Thanks for putting this together.

It looks like you're having some trailing whitespace issues which are causing the pep8 tests to fail. if you run `autopep8` on the file, that should address it and then I can merge this in. Thanks for the contribution!

**Comment by hugofvs** [comment]
Sorry for taking too long to fix this.

**Comment by hugofvs** [comment]
@deanmalmgren any news when this can be merged?

**Comment by deanmalmgren** [comment]
Thanks for the friendly ping. I just pushed the latest release to PyPi :)

**Pull request merged**
