### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by davidread**
Most of the work is from @jrings but I added:
* rebase
* a fix for a py2-only sorting thing, that was recently added
* Travis also tests on python 3
* PEP8

### CODE REVIEW

**Comment by davidread** [comment]
Hi @deanmalmgren, it would be great to get this merged, when you get a chance

**Comment by deanmalmgren** [comment]
@davidread this is great; thanks! Merging now. I'll release on pypi momentarily.

**Comment by ivyleavedtoadflax** [comment]
Great - @deanmalmgren glad you merged this. I had been developing on a fork https://github.com/ukgovdatascience/scrubadub. Happy to contribute new filths/detectors back here. Would still need to default to GB phone numbers rather than US though.

**Comment by deanmalmgren** [comment]
@ivyleavedtoadflax oh wow; that's great that you've been jamming on this! nice :)

i'm fine with the contributions—in fact, i'd love to include them. i didn't flip through all of the commits, but can you make sure the additional filths are documented and tested?

re: default phone numbers, I believe you can change the default by doing something like this:

```python
import scrubadub

# since this is a class attribute, this will change it for all PhoneDectector instances
scrubadub.detectors.PhoneDectector.region = 'GB'

scrubadub.clean("my number is +44 20 7123 4567")
```

**Comment by ivyleavedtoadflax** [comment]
Ah I missed that, that's great. I'll have a read of your contributing guidelines, and submit some PRs next week. Thanks!

**Comment by deanmalmgren** [comment]
That's terrific! I'll keep an eye out for your PRs. :)

**Comment by davidread** [comment]
Awesome @deanmalmgren, thanks for this neat package in the first place.

**Pull request merged**
